### ISSUE TITLE
 %publish  ->  Expected URL scheme 'http' or 'https' but was 'sysmlapiserver

### ISSUE THREAD

**Issue by PatrickF-mbse** [gorenje/sysmlv2-jupyter-docker#19]
Hi, thank you for the update to 2024.  I installed this new version and every working fine except the %publish.  This time I tried to use an Ubuntu server so maybe this is the reasons ( more strict rules than windows localhost?). 

I was wondering if anyone using it on linux and experienced the same error for the %publish command?

Thank you very much 

**%publish SysMLv2Model**

API base path: sysmlapiserver:9000
Processing
java.lang.IllegalArgumentException: **Expected URL scheme 'http' or 'https' but was 'sysmlapiserver'**
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1327)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.Request$Builder.url(Request.java:165)
	at org.omg.sysml.ApiClient.buildRequest(ApiClient.java:1035)
	at org.omg.sysml.ApiClient.buildCall(ApiClient.java:1010)
	at org.omg.sysml.api.ProjectApi.postProjectCall(ProjectApi.java:491)
	at org.omg.sysml.api.ProjectApi.postProjectValidateBeforeCall(ProjectApi.java:498)
	at org.omg.sysml.api.ProjectApi.postProjectWithHttpInfo(ProjectApi.java:539)
	at org.omg.sysml.api.ProjectApi.postProject(ProjectApi.java:519)
	at org.omg.sysml.util.traversal.facade.impl.ApiElementProcessingFacade.commit(ApiElementProcessingFacade.java:124)
	at org.omg.sysml.interactive.SysMLInteractive.publish(SysMLInteractive.java:396)
	at org.omg.sysml.jupyter.kernel.magic.Publish.publish(Publish.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.spencerpark.jupyter.kernel.magic.registry.Magics.invoke(Magics.java:89)
	at io.github.spencerpark.jupyter.kernel.magic.registry.Magics.access$000(Magics.java:8)
	at io.github.spencerpark.jupyter.kernel.magic.registry.Magics$LineReflectionMagicFunction.execute(Magics.java:149)
	at io.github.spencerpark.jupyter.kernel.magic.registry.Magics.applyLineMagic(Magics.java:26)
	at org.omg.sysml.jupyter.kernel.SysMLKernel.eval(SysMLKernel.java:92)
	at io.github.spencerpark.jupyter.kernel.BaseKernel.handleExecuteRequest(BaseKernel.java:334)
	at io.github.spencerpark.jupyter.channels.ShellChannel.lambda$bind$0(ShellChannel.java:64)
	at io.github.spencerpark.jupyter.channels.Loop.lambda$new$0(Loop.java:21)
	at io.github.spencerpark.jupyter.channels.Loop.run(Loop.java:78)

**Comment by gorenje** [comment]
Since I don't use this any longer, I can only guess.

The only place that I see that sets this value is [here](https://github.com/gorenje/sysmlv2-jupyter-docker/blob/cecbad6c318cd22b34ad0a6e24e58d5a70796abe/Dockerfile.jupyter#L86-L87) where the publish command is configured.

I don't really see the issue since the prefix `http://` is included in the specification of the api server.
